# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Download gtfs-realtime schema
        run: |
          curl -o gtfs-realtime-schema.txt https://raw.githubusercontent.com/google/transit/master/gtfs-realtime/proto/gtfs-realtime.proto
      
      - name: List files
        run: ls -la
      
      - name: Check protobuf.js content
        run: |
          if [ -f protobuf.js ]; then
            echo "protobuf.js exists. First 10 lines:"
            head -n 10 protobuf.js
          else
            echo "protobuf.js does not exist"
          fi
      
      - name: Modify protobuf.js
        run: |
          if [ -f protobuf.js ]; then
            sed -i 's|https://raw.githubusercontent.com/google/transit/master/gtfs-realtime/proto/gtfs-realtime.proto|gtfs-realtime-schema.txt|g' protobuf.js
            echo "Modified protobuf.js"
          else
            echo "protobuf.js does not exist, skipping modification"
          fi
      
      - name: Add timestamp to script.js
        run: |
          echo "// Last updated: $(date)" >> script.js
      
      - name: Setup Pages
        uses: actions/configure-pages@v4
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'
      
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
